name: Publish Wiki

on:
  push:
    branches: [main]
    paths:
      - "wiki/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Publish wiki pages
        uses: Andrew-Chen-Wang/github-wiki-action@50650fccf3a10f741995523cf9708c53cec8912a # v4
        with:
          path: wiki/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.WIKI_PAT }}
