name: Publish Wiki

on:
  push:
    branches: [main]
    paths:
      - "wiki/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Publish wiki pages
        uses: Andrew-Chen-Wang/github-wiki-action@64efa0a9436db17670a2259e0ac249d6f08bb352 # v5.0.4
        with:
          path: wiki/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.WIKI_PAT }}
