name: Publish Wiki

on:
  push:
    branches: [main]
    paths:
      - "wiki/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Publish wiki pages
        uses: Andrew-Chen-Wang/github-wiki-action@50650fccf3a10f741995523cf9708c53cec8912a # v4
        with:
          path: wiki/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
